using Presentation.ViewModels;
using System;
using System.Collections.Generic;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace Presentation.Views
{
    /// <summary>
    /// Логика взаимодействия для PacketsView.xaml
    /// </summary>
    public partial class PacketsView : UserControl
    {

        public PacketsView()
        {
            InitializeComponent();

            // attach to DataContextChanged to wire up PropertyChanged on VM
            this.DataContextChanged += PacketsView_DataContextChanged;

            // if DataContext already set at construction time
            if (this.DataContext is System.ComponentModel.INotifyPropertyChanged initial)
                initial.PropertyChanged += Vm_PropertyChanged;
        }

        // Wire up/unwire VM.PropertyChanged when DataContext changes
        private void PacketsView_DataContextChanged(object? sender, DependencyPropertyChangedEventArgs e)
        {
            if (e.OldValue is System.ComponentModel.INotifyPropertyChanged oldVm)
                oldVm.PropertyChanged -= Vm_PropertyChanged;

            if (e.NewValue is System.ComponentModel.INotifyPropertyChanged newVm)
                newVm.PropertyChanged += Vm_PropertyChanged;
        }

        private void Vm_PropertyChanged(object? sender, System.ComponentModel.PropertyChangedEventArgs e)
        {
            if (e.PropertyName == nameof(Presentation.ViewModels.MainViewModel.SelectedPacket))
            {
                var vm = DataContext as Presentation.ViewModels.MainViewModel;
                if (vm?.SelectedPacket != null)
                {
                // Scroll selected into view on UI thread, using FindName to get the DataGrid
                var dg = this.FindName("PacketsDataGrid") as DataGrid;
                dg?.ScrollIntoView(vm.SelectedPacket);
                }
            }
        }

        private void ProtocolTreeItem_MouseEnter(object sender, MouseEventArgs e)
        {
            if (DataContext is not MainViewModel vm)
                return;

            // DataContext may be ProtocolNode; TreeViewItems are generated by WPF and
            // sender can be a TreeViewItem whose DataContext is a ProtocolNode.
            if (sender is not TreeViewItem uiItem)
                return;

            // support both Tag and DataContext.Tag (for our ProtocolNode) to get the range
            object? tag = uiItem.Tag ?? (uiItem.DataContext as Presentation.Helpers.ProtocolNode)?.Tag;
            if (tag is ValueTuple<int, int> range)
                vm.SelectedRange = range;
            else
                vm.SelectedRange = null;
        }

        private void ProtocolTreeItem_Selected(object sender, RoutedEventArgs e)
        {
            // щоб при кліку теж гарантовано підсвічувало
            ProtocolTreeItem_MouseEnter(sender, null!);
        }

        private void ProtocolTree_PreviewMouseMove(object sender, MouseEventArgs e)
        {
            if (DataContext is not MainViewModel vm)
                return;

            if (sender is not TreeView tree) return;

            Point pt = e.GetPosition(tree);
            HitTestResult hit = VisualTreeHelper.HitTest(tree, pt);
            if (hit == null)
            {
                vm.SelectedRange = null;
                return;
            }

            DependencyObject current = hit.VisualHit;
            while (current != null && current is not TreeViewItem)
            {
                current = VisualTreeHelper.GetParent(current);
            }

            if (current is TreeViewItem tvi)
            {
                object? tag = tvi.Tag ?? (tvi.DataContext as Presentation.Helpers.ProtocolNode)?.Tag;
                if (tag is ValueTuple<int, int> range)
                    vm.SelectedRange = range;
                else
                    vm.SelectedRange = null;
            }
            else
            {
                vm.SelectedRange = null;
            }
        }

        private void ProtocolTree_MouseLeave(object sender, MouseEventArgs e)
        {
            if (DataContext is not MainViewModel vm) return;
            vm.SelectedRange = null;
        }
    }
}
